import uuid
from datetime import date
from decimal import Decimal

from sqlalchemy import CheckConstraint, ForeignKey, Numeric, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDPKMixin

VALID_BILL_STATUSES = ("unpaid", "paid", "overdue", "void")

_STATUS_CHECK_SQL = (
    "status IN (" + ",".join(f"'{status}'" for status in VALID_BILL_STATUSES) + ")"
)
_VENDOR_CHECK_SQL = "subcontractor_id IS NOT NULL OR vendor_name IS NOT NULL"


class Bill(Base, UUIDPKMixin, TimestampMixin):
    __tablename__ = "bills"

    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False
    )
    # Nullable: NULL for company-wide overhead bills with no Project.
    project_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=True
    )
    # Nullable: NULL for a vendor that isn't a tracked Subcontractor.
    subcontractor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("subcontractors.id"), nullable=True
    )
    # Required only when subcontractor_id is NULL — enforced by the
    # ck_bills_vendor CheckConstraint below, not at the Python/Pydantic layer
    # alone (defense in depth, matching this codebase's general convention
    # of mirroring app-layer validation with a DB constraint where possible).
    vendor_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # The vendor's own reference number, free text — never generated by us
    # (unlike Invoice.invoice_number).
    bill_number: Mapped[str | None] = mapped_column(String(50), nullable=True)
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="unpaid")
    due_date: Mapped[date | None] = mapped_column(nullable=True)

    __table_args__ = (
        CheckConstraint(_STATUS_CHECK_SQL, name="ck_bills_status"),
        CheckConstraint(_VENDOR_CHECK_SQL, name="ck_bills_vendor"),
    )
