import { NextRequest, NextResponse } from "next/server";
import { apiFetch } from "@/lib/api/client";
import { errorResponse } from "@/lib/api/handler-utils";
import { missingPlatformTokenResponse, platformToken } from "@/lib/platform/session";

export async function GET(request: NextRequest) {
  const token = platformToken(request);
  if (!token) return missingPlatformTokenResponse();
  try {
    const data = await apiFetch("/platform/companies", "get", {
      accessToken: token,
      query: {
        search: request.nextUrl.searchParams.get("search") ?? undefined,
        roots_only: request.nextUrl.searchParams.get("roots_only") ?? undefined,
        include_deleted: request.nextUrl.searchParams.get("include_deleted") ?? undefined,
        cursor: request.nextUrl.searchParams.get("cursor") ?? undefined,
        limit: request.nextUrl.searchParams.get("limit") ?? undefined,
      },
    });
    return NextResponse.json(data);
  } catch (err) {
    return errorResponse(err, "Failed to load tenants");
  }
}

/**
 * Creates a tenant: company, owner user, membership, trial subscription.
 *
 * The response carries a one-time password the operator must convey to the
 * customer — it is generated by the backend, stored only as a hash, and
 * returned here and nowhere else. Nothing caches or logs this response
 * body; `Cache-Control: no-store` is set for the same reason the login
 * route sets it.
 */
export async function POST(request: NextRequest) {
  const token = platformToken(request);
  if (!token) return missingPlatformTokenResponse();
  const body = await request.json();
  try {
    const data = await apiFetch("/platform/companies", "post", {
      accessToken: token,
      body,
    });
    const response = NextResponse.json(data, { status: 201 });
    response.headers.set("Cache-Control", "no-store");
    return response;
  } catch (err) {
    return errorResponse(err, "Failed to create the tenant");
  }
}
